public class Main {

    public static void stars(int n) {
        for (int i = 0; i < n; i++) System.out.print('*');
    }
    public static void space(int n) {
        for (int i = 0; i < n; i++) System.out.print(' ');
    }
    public static void main(String[] args) {
        System.out.print("* ");
        System.out.print("*");
        for (int i = 0; i < 5; i++) System.out.print(" ");
        System.out.print("* ");
        for (int i = 0; i < 4; i++) System.out.print("*");
        System.out.print(" ");
        System.out.print("*");
        space(4);
        stars(1);
        space(1);
        stars(5);
        space(5);
        stars(5);
        space(3);
        stars(1);
        space(5);
        stars(1);
        System.out.println();
        stars(1);
        space(1);
        stars(2);
        space(4);
        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        space(4);
        stars(1);
        space(1);
        stars(1);
        space(5);
        stars(1);
        space(1);
        stars(1);
        space(7);
        stars(1);
        space(1);
        stars(2);
        space(4);
        stars(1);
        System.out.println();
        stars(1);
        space(1);
        stars(1);
        space(1);
        stars(1);
        space(3);
        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        space(4);
        stars(1);
        space(1);
        stars(1);
        space(5);
        stars(1);
        space(1);
        stars(1);
        space(7);
        stars(1);
        space(1);
        stars(1);
        space(1);
        stars(1);
        space(3);
        stars(1);
        System.out.println();

        System.out.print("* ");
        System.out.print("*");
        space(2);
        System.out.print("*");
        space(2);
        stars(1);
        space(1);
        stars(4);
        space(1);
        stars(1);
        space(4);
        stars(1);
        space(1);
        stars(5);
        space(3);
        stars(1);
        space(7);
        stars(1);
        space(1);
        stars(1);
        space(2);
        stars(1);
        space(2);
        stars(1);
        System.out.println();

        stars(1);
        space(1);
        stars(1);
        space(3);
        stars(1);
        space(1);
        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        space(4);
        stars(1);
        space(1);
        stars(1);
        space(5);
        stars(1);
        space(1);
        stars(1);
        space(7);
        stars(1);
        space(1);
        stars(1);
        space(3);
        stars(1);
        space(1);
        stars(1);
        System.out.println();

        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        space(4);
        stars(1);
        space(1);
        stars(1);
        space(5);
        stars(1);
        space(1);
        stars(1);
        space(7);
        stars(1);
        space(1);
        stars(1);
        space(4);
        stars(1);
        stars(1);
        System.out.println();

        System.out.print("* ");
        System.out.print("*");
        for (int i = 0; i < 5; i++) System.out.print(" ");
        System.out.print("* ");
        for (int i = 0; i < 4; i++) System.out.print("*");
        System.out.print(" ");
        System.out.print("*");
        stars(4);
        stars(1);
        space(1);
        stars(1);
        space(5);
        stars(1);
        space(3);
        stars(5);
        space(3);
        stars(1);
        space(5);
        stars(1);
    }
}